### ISSUE TITLE
injection dont stop

### ISSUE THREAD

**Issue by swesws** [reveny/Android-GUI-Injector#28]
After injecting the modification, I can't turn it off. after restarting android is still automatically injected into the game. I tried to remove GUI Injector but even after removal the modification was injected into the game. root: kernelsu, android14

**Comment by reveny** [comment]
Please provide more information about the device used including KSU Modules installed and version of the Injector.
This issue seems very weird to me as the Injector does not run or start on boot and does not persist on the device after uninstalling. Please also see if deleting the target library from disk helps. If it still Injects after deleting the library after boot then there is something seriously wrong with the device.

**Comment by swesws** [comment]
Redmi Note 12 4g NFC device on Crdroid 10.8; kernelsu modules: Zygisk -Lsposed; Zugisk Assistant; ZygiskNext. I wanted to say that after I injected the modification, the Native Detector began to show: Found Magisk module (libmodmenu.so) and Found Inject (1).

**Comment by swesws** [comment]
after restarting the device the injection is still detected. Now I'll try to remove the modification .so file.

**Comment by reveny** [comment]
Android-GUI-Injector is not detected as "Found Magisk Module". You may have a zygisk module installed that is causing this. For further checking use the latest version of Native Detector: 
https://github.com/reveny/Android-Native-Root-Detector/releases/tag/v6.5.2
